set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property PACKAGE_PIN AC26 [get_ports RGMII_0_rx_ctl]
set_property PACKAGE_PIN AE27 [get_ports RGMII_0_tx_ctl]
set_property PACKAGE_PIN AF27 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN Y30 [get_ports MDIO_PHY_0_mdio_io]
set_property PACKAGE_PIN AF28 [get_ports {RGMII_0_td[0]}]
set_property PACKAGE_PIN AG27 [get_ports {RGMII_0_td[1]}]
set_property PACKAGE_PIN AE28 [get_ports {RGMII_0_td[2]}]
set_property PACKAGE_PIN AG29 [get_ports {RGMII_0_td[3]}]
set_property PACKAGE_PIN AD25 [get_ports {RGMII_0_rd[0]}]
set_property PACKAGE_PIN AD26 [get_ports {RGMII_0_rd[1]}]
set_property PACKAGE_PIN AE26 [get_ports {RGMII_0_rd[2]}]
set_property PACKAGE_PIN AD29 [get_ports {RGMII_0_rd[3]}]
set_property PACKAGE_PIN Y27 [get_ports MDIO_PHY_0_mdc]
set_property PACKAGE_PIN AB27 [get_ports RGMII_0_rxc]
set_property PACKAGE_PIN AA30 [get_ports ENET0_EXT_INTIN_0]
set_property PACKAGE_PIN Y28 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN AE17 [get_ports {GPIO_0_0_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_txc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_EXT_INTIN_0]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]

set_property SLEW FAST [get_ports {RGMII_0_td[3]}]
set_property SLEW FAST [get_ports {RGMII_0_td[2]}]
set_property SLEW FAST [get_ports {RGMII_0_td[1]}]
set_property SLEW FAST [get_ports {RGMII_0_td[0]}]
set_property SLEW FAST [get_ports RGMII_0_txc]
set_property SLEW FAST [get_ports RGMII_0_tx_ctl]

create_clock -period 8.000 -name rgmii_rxc -add [get_ports RGMII_0_rxc]

set_property IDELAY_VALUE 8 [get_cells -hier -filter {name =~ *zynq_top_gmii_to_rgmii_0_0_core/*delay_rgmii_rx_ctl          }]
set_property IDELAY_VALUE 8 [get_cells -hier -filter {name =~ *zynq_top_gmii_to_rgmii_0_0_core/*delay_rgmii_rxd*            }]
set_property IODELAY_GROUP gpr1 [get_cells -hier -filter {name =~ *zynq_top_gmii_to_rgmii_0_0_core/*delay_rgmii_rx_ctl          }]
set_property IODELAY_GROUP gpr1 [get_cells -hier -filter {name =~ *zynq_top_gmii_to_rgmii_0_0_core/*delay_rgmii_rxd*            }]
set_property IODELAY_GROUP gpr1 [get_cells -hier -filter {name =~ *i_zynq_top_gmii_to_rgmii_0_0_idelayctrl}]


#set_property IDELAY_VALUE 8 [get_cells zynq_top_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/zynq_top_gmii_to_rgmii_0_0_core/i_gmii_to_rgmii/i_gmii_to_rgmii/gen_rgmii_rx_zq.delay_rgmii_rx_ctl]
#set_property IDELAY_VALUE 8 [get_cells {zynq_top_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/zynq_top_gmii_to_rgmii_0_0_core/i_gmii_to_rgmii/i_gmii_to_rgmii/gen_rgmii_rx_zq.rxdata_bus[*].delay_rgmii_rxd}]
#set_property IODELAY_GROUP gpr1 [get_cells zynq_top_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/zynq_top_gmii_to_rgmii_0_0_core/i_gmii_to_rgmii/i_gmii_to_rgmii/gen_rgmii_rx_zq.delay_rgmii_rx_ctl]
#set_property IODELAY_GROUP gpr1 [get_cells {zynq_top_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/zynq_top_gmii_to_rgmii_0_0_core/i_gmii_to_rgmii/i_gmii_to_rgmii/gen_rgmii_rx_zq.rxdata_bus[*].delay_rgmii_rxd}]
#set_property IODELAY_GROUP gpr1 [get_cells zynq_top_i/gmii_to_rgmii_0/U0/i_zynq_top_gmii_to_rgmii_0_0_idelayctrl]

set_clock_groups -name gt_async_clk_group -asynchronous \
        -group [get_clocks -of_objects [get_pins zynq_top_i/processing_system7_0/FCLK_CLK0]] \
        -group [get_clocks -of_objects [get_pins zynq_top_i/processing_system7_0/FCLK_CLK1]]
